// <auto-generated />
using System;
using DigitalHearth.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalHearth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322192951_RenameImageUrlToImageData")]
    partial class RenameImageUrlToImageData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalHearth.Api.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekResetDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Households");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageData")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("MealLibrary");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotifPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "TaskId")
                        .IsUnique();

                    b.ToTable("NotifPreferences");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastCompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("LastCompletedByUserId");

                    b.ToTable("RecurringTasks");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.TaskCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskCompletions");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.WeeklyMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int?>("MealLibraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("WeekOf")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MealLibraryId");

                    b.HasIndex("HouseholdId", "WeekOf");

                    b.ToTable("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.User", "CreatedByUser")
                        .WithMany("CreatedMeals")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("MealLibrary")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotifPreference", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.RecurringTask", "Task")
                        .WithMany("NotifPreferences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("NotifPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.PushSubscription", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("Tasks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "LastCompletedByUser")
                        .WithMany()
                        .HasForeignKey("LastCompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("LastCompletedByUser");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.TaskCompletion", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.RecurringTask", "Task")
                        .WithMany("Completions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("Completions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.WeeklyMeal", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("WeeklyMeals")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.MealLibrary", "MealLibrary")
                        .WithMany("WeeklyMeals")
                        .HasForeignKey("MealLibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("MealLibrary");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.Household", b =>
                {
                    b.Navigation("MealLibrary");

                    b.Navigation("Members");

                    b.Navigation("Tasks");

                    b.Navigation("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.Navigation("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("NotifPreferences");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("CreatedMeals");

                    b.Navigation("NotifPreferences");

                    b.Navigation("PushSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
