// <auto-generated />
using System;
using DigitalHearth.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalHearth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406012736_AddRecurringTaskIsOneTime")]
    partial class AddRecurringTaskIsOneTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalHearth.Api.Models.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("GoalMealsPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ImageGenCount")
                        .HasColumnType("integer");

                    b.Property<int>("ImageGenMonth")
                        .HasColumnType("integer");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinCodeCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MonthlyImageBudget")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekResetDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Households");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImageGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealLibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MealLibraryId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealLibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealLibraryId");

                    b.HasIndex("UserId", "MealLibraryId")
                        .IsUnique();

                    b.ToTable("MealFavorites");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("MealLibrary");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotifPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "TaskId")
                        .IsUnique();

                    b.ToTable("NotifPreferences");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("PushSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecurringTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecurringTaskId");

                    b.HasIndex("PushSubscriptionId", "RecurringTaskId", "DueAt")
                        .IsUnique();

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulPushAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastCompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("LastCompletedByUserId");

                    b.ToTable("RecurringTasks");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.TaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskCompletions");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.UserNotifSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("LongTermTaskNotifs")
                        .HasColumnType("boolean");

                    b.Property<bool>("MealPlannerNotifs")
                        .HasColumnType("boolean");

                    b.Property<int?>("MediumTermDaysAhead")
                        .HasColumnType("integer");

                    b.Property<bool>("MediumTermTaskNotifs")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShortTermTaskNotifs")
                        .HasColumnType("boolean");

                    b.Property<bool>("TaskCompletedNotifs")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaskReminderHour")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserNotifSettings");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.WeeklyMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCooked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MealLibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("WeekOf")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MealLibraryId");

                    b.HasIndex("HouseholdId", "WeekOf");

                    b.ToTable("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.Image", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.MealLibrary", "MealLibrary")
                        .WithOne("Image")
                        .HasForeignKey("DigitalHearth.Api.Models.Image", "MealLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealLibrary");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealFavorite", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.MealLibrary", "MealLibrary")
                        .WithMany()
                        .HasForeignKey("MealLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealLibrary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.User", "CreatedByUser")
                        .WithMany("CreatedMeals")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("MealLibrary")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotifPreference", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.RecurringTask", "Task")
                        .WithMany("NotifPreferences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("NotifPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.NotificationLog", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.PushSubscription", "PushSubscription")
                        .WithMany()
                        .HasForeignKey("PushSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.RecurringTask", "RecurringTask")
                        .WithMany()
                        .HasForeignKey("RecurringTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PushSubscription");

                    b.Navigation("RecurringTask");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.PushSubscription", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("Tasks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "LastCompletedByUser")
                        .WithMany()
                        .HasForeignKey("LastCompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("LastCompletedByUser");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.TaskCompletion", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.RecurringTask", "Task")
                        .WithMany("Completions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithMany("Completions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.UserNotifSettings", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.User", "User")
                        .WithOne("NotifSettings")
                        .HasForeignKey("DigitalHearth.Api.Models.UserNotifSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.WeeklyMeal", b =>
                {
                    b.HasOne("DigitalHearth.Api.Models.Household", "Household")
                        .WithMany("WeeklyMeals")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalHearth.Api.Models.MealLibrary", "MealLibrary")
                        .WithMany("WeeklyMeals")
                        .HasForeignKey("MealLibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("MealLibrary");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.Household", b =>
                {
                    b.Navigation("MealLibrary");

                    b.Navigation("Members");

                    b.Navigation("Tasks");

                    b.Navigation("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.MealLibrary", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("WeeklyMeals");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.RecurringTask", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("NotifPreferences");
                });

            modelBuilder.Entity("DigitalHearth.Api.Models.User", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("CreatedMeals");

                    b.Navigation("NotifPreferences");

                    b.Navigation("NotifSettings");

                    b.Navigation("PushSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
